server:
  port: 8888
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 60s
  application:
    name: chok
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
#  threads:
#    virtual:
#      enabled: true
security:
  ignore-urls:
    - /favicon.ico
    - /login
    - /logout
    - /refreshToken
    - /register
    - /validateCode
    - /wx/portal/{appId}
    - /wx/authorization/{appId}
    - /wx/authorization/{appId}/callback
  user-type:
    admin:
      code: admin
      relation-table: rel_admin_role
      relation-id: admin_id
    user:
      code: user
      relation-table: rel_user_role
      relation-id: user_id
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - refresh
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true